### ISSUE TITLE
[BugFix] Layout is breaking on last pages.

### ISSUE THREAD

**Issue by dilannery** [devfsa/overflow-news#21]
![overflow news_posts_449](https://user-images.githubusercontent.com/90305/37924872-85d79ca0-3109-11e8-9ff6-b3cadd3bee21.png)

**Comment by di3goleite** [comment]
@RodolfoSilva this one is that issue that you talked with me?

**Comment by franciscobrba** [comment]
#### wtf!!! 1110px?

![capture](https://user-images.githubusercontent.com/20749018/37940406-d965ca88-313e-11e8-84c6-369fd235b6fd.PNG)

#### May it should be 65px 🤔 
![screenshot 56](https://user-images.githubusercontent.com/20749018/37940456-0e90cab4-313f-11e8-8c3f-e537b4b2165f.png)

#### But i don't like to have magic numbers in CSS... Something looks very wrong

**Comment by RodolfoSilva** [comment]
@di3goleite yes, kkkkkk

**Comment by RodolfoSilva** [comment]
Fixed in #35

**Comment by RodolfoSilva** [comment]
![image](https://user-images.githubusercontent.com/1703020/44183056-dbc3e600-a0df-11e8-81d3-034ef364ed1c.png)
