### ISSUE TITLE
[BugFix] Error: the deferred callback has already been called

### ISSUE THREAD

**Issue by di3goleite** [devfsa/overflow-news#30]
![](https://i.imgur.com/yEVitHm.png)

**Comment by rafaelverger** [comment]
This is probably being caused by a "double" call of `then` in a promise request

**Comment by rafaelverger** [comment]
I don't know if it is possible to happen but looks like `on(error)` and `on(response)` are being called at the same time here: https://github.com/devfsa/overflow-news/blob/master/src/lib/job.js#L1-L30

How can this error be reproduced, @di3goleite ?  I have a fix in mind but would be nice to have a how to reproduce to test the solution...

**Comment by di3goleite** [comment]
Great catch @rafaelverger . I'll try to reproduce this issue and share more information here. Do you know what should be the best approach to solve this possible `on(error)` and `on(response)` issue?

**Comment by rafaelverger** [comment]
Probably return the result of `request` an set `on(error)` and `on(response)` separatedly, like this:
```js
cons result = request(url);
result.on('error', errorHandler);
result.on('response', responseHandler);
```

**Comment by di3goleite** [comment]
@rafaelverger I'm thinking to use Sentry as Error Handler. What do you think? https://docs.sentry.io/clients/node/#reporting-errors

**Comment by rafaelverger** [comment]
I think that will be great!
